//Sentecia para crear una nueva orden.
export const SqlInsertOrder = () => {
    return `INSERT INTO GRUPO_EMPRESARIAL_HT.HT_ORDERS (
      CLIENTEID,
      ESTADO,
      FECHA,
      FECHAACTUALIZACION,
      FECHACREACION,
      FORMADEPAGO,
      GUARDADO,
      HORA,
      LATITUD,
      LONGITUD,
      OBSERVACIONES,
      ONLINE,
      SUBTOTAL,
      TOTAL,
      TOTALIVA,
      USUARIOAACTUALIZACION,
      VENDEDOR,
      VENDEDORID,
      LOCALCLIENTE_ID,
      EMPRESA,
      FECHAFACTURACION,
      NUMEROFACTURAE4,
      NUMEROFACTURAHIPERTRONICS,
      NUMEROFACTURALIDENAR,
      NUMEROGUIA,
      OBSERVACIONESB,
      NOTACLIENTE,
      USUARIOAPROBO,
      PLANPAGOSTOMEBAMBA_ID,
      APLICACIONORIGEN,
      COMENTARIOENTREGA,
      FECHAENTREGA,
      NOMBREUSUARIOENTREGA,
      USUARIOENTREGA_ID,
      FECHAENTREGASOLICITADA,
      IDUSUARIOENTREGARA,
      NOMBREUSUARIOENTREGARA,
      COURIER,
      USUARIOENTREGABODEGA_ID,
      BODEGA,
      PEDIDOCATEGORIAPROPIA,
      IMAGENA,
      IMAGENB,
      IMAGEN,
      IMAGENGUIA,
      FECHAAPROBO,
      DOCNUM
  ) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
  )`;
};

export const ParamsOrder = (body) => [
    body.CLIENTEID || 0,
    body.ESTADO || 0,
    body.FECHA || '',
    body.FECHAACTUALIZACION || '',
    body.FECHACREACION || '',
    body.FORMADEPAGO || '',
    body.GUARDADO || 0,
    body.HORA || '',
    body.LATITUD || 0.00,
    body.LONGITUD || 0.00,
    body.OBSERVACIONES || '',
    body.ONLINE || true,
    body.SUBTOTAL || 0.00,
    body.TOTAL || 0.00,
    body.TOTALIVA || 0.00,
    body.USUARIOAACTUALIZACION || '',
    body.VENDEDOR || '',
    body.VENDEDORID || 0,
    body.LOCALCLIENTE_ID || 0,
    body.EMPRESA || '',
    body.FECHAFACTURACION || '',
    body.NUMEROFACTURAE4 || '',
    body.NUMEROFACTURAHIPERTRONICS || '',
    body.NUMEROFACTURALIDENAR || '',
    body.NUMEROGUIA || '',
    body.OBSERVACIONESB || '',
    body.NOTACLIENTE || '',
    body.USUARIOAPROBO || '',
    body.PLANPAGOSTOMEBAMBA_ID || 0,
    body.APLICACIONORIGEN || '',
    body.COMENTARIOENTREGA || '',
    body.FECHAENTREGA || '',
    body.NOMBREUSUARIOENTREGA || '',
    body.USUARIOENTREGA_ID || 0,
    body.FECHAENTREGASOLICITADA || '',
    body.IDUSUARIOENTREGARA || 0,
    body.NOMBREUSUARIOENTREGARA || '',
    body.COURIER || '',
    body.USUARIOENTREGABODEGA_ID || 0,
    body.BODEGA || 0,
    body.PEDIDOCATEGORIAPROPIA || 0,
    body.IMAGENA || '',
    body.IMAGENB || '',
    body.IMAGEN || '',
    body.IMAGENGUIA || '',
    body.FECHAAPROBO || '',
    body.DOCNUM || 0];


// export const QuerySearch = () => `SELECT U.*
// FROM GRUPO_EMPRESARIAL_HT.HT_ORDERS AS U
// JOIN (SELECT CURRENT_IDENTITY_VALUE() AS ID FROM DUMMY) AS I
// ON U.ID = I.ID;`;

