// import mongoose from 'mongoose';
//
// const userSchema = mongoose.Schema({
//
//     id: { type: String },
//     clave: { type: String, required:  true },
//     correo: { type: String },
//     usuario: { type: String, required: true },
//     rol: { type: String },
//     usuarioa: { type: String },
//     agencias: { type: String },
//     lugar: { type: String },
//     cambiar: { type: Number },
//     empleadodesde: { type: String },
//     fotourl: { type: String },
//     mac: { type: String },
//     macb: { type: String },
//     grupo: { type: String },
//     extension: { type: Number},
//     tipo: { type: Number },
//     perfilvendedor: { type: String },
//     //Revisar
//     clienteasociadoempresa: { type: String },
//     nombreempresa: { type: String },
//     perfilempresa: { type: Number },
//     precioempresa: { type: String },
//     subperfilempresa: { type: Number },
//     usuariocreacion: { type: String },
//     //Revisar
//     ciudad: { type: String },
//     vendedorempresa: { type: String },
//     token: { type: String },
//     perfilretail: { type: Number },
//     subperfilretail: { type: String },
//     tokenretail: { type: String },
//     categoria: { type: String },
//     perfilterreno: { type: Number },
//     tokenterreno: { type: String },
//     plantillaa: { type: String },
//     plantillab: { type: String },
//     plantillac: { type: String },
//     precioretailpersonaliza: { type: String },
//     bodegadistribuidores: { type: Number },
//     facturador: { type: Boolean,
//                    default: false },
//     cobrador: { type: Number },
//     disponibleentregas: { type: Boolean ,
//                             default: false},
//     menuconsumidorfinal: { type: Number },
//     prime: { type: Number },
//     codigopac: { type: String },
//     celular: { type: String },
//     registrado: { type: Number },
//     verificado: { type: Number },
//     fechaactualizacionhtplus: { type: String },
//     fechacreacion: { type: Date,
//     default: new Date()} ,
//     usuarioactualizacionhtplus: { type: String },
//     todosclientes: { type: Number },
//     perfilmenudis: { type: String },
//     departamento: { type: String },
//     //fecha creacion registro
//     createdAt: {
//         type: Date,
//         default: new Date(),
//     },
//
// })
//
// export default mongoose.model('User', userSchema);